services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  # db:
  #   image: mariadb:11
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MARIADB_ROOT_PASSWORD: ${DB_PASS:-secret}
  #     MARIADB_DATABASE: ${DB_NAME:-app}
  #   volumes:
  #     - db_data:/var/lib/mysql

  # db:
  #   image: postgres:17-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: ${DB_NAME:-app}
  #     POSTGRES_USER: ${DB_USER:-app}
  #     POSTGRES_PASSWORD: ${DB_PASS:-secret}
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
